from abc import ABC, abstractmethod
from typing import Any


class BaseCacheProvider(ABC):

    @abstractmethod
    async def get(self, key: str) -> Any | None:
        ...

    @abstractmethod
    async def set(self, key: str, value: str, ttl: int | None = None) -> None:
        ...

    @abstractmethod
    async def delete(self, key: str) -> None:
        ...

    @abstractmethod
    async def exists(self, key: str) -> bool:
        ...

    @abstractmethod
    async def sadd(self, key: str, value: str) -> None:
        ...

    @abstractmethod
    async def sismember(self, key: str, value: str) -> bool:
        ...

    @abstractmethod
    async def rpush(self, key: str, value: str) -> None:
        ...

    @abstractmethod
    async def set_nx(self, key: str, value: str, ttl: int | None = None) -> bool:
        ...


class BaseCacheBackend:
    async def get(self, key: str) -> Any | None: ...
    async def set(self, key: str, value: str, ttl: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
    async def sadd(self, key: str, value: str) -> None: ...
    async def sismember(self, key: str, value: str) -> bool: ...
    async def rpush(self, key: str, value: str) -> None: ...
    async def set_nx(self, key: str, value: str, ttl: int | None = None) -> bool: ...
